const colorPalettes = {
    gray: {
      primary: 'bg-gray-800',
      hover: 'hover:bg-gray-700',
      ring: 'focus:ring-gray-400',
      bg: 'bg-gray-800 backdrop-blur-md',
      text: 'text-gray-200',
      inputBg: 'bg-gray-900',
      inputBorder: 'border-gray-700',
      inputFocus: 'focus:ring-gray-500 focus:border-gray-400',
      placeholder: 'placeholder-gray-400',
      tabActive: 'bg-gray-700 text-white',
      tabHover: 'hover:bg-gray-800',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-gray-700 hover:bg-gray-600 text-white',
      buttonText: '#fafafa',
      borderColor: 'border-gray-600',
      buttonHover: 'hover:bg-gray-600',
      softShadow: 'shadow-md',
      iconColor: 'text-gray-300', // Icon color based on primary gray
    },
    darkBlue: {
      primary: 'bg-[#0a1a2e]',
      hover: 'hover:bg-[#1d2d47]',
      ring: 'focus:ring-[#3e4b67]',
      bg: 'bg-[#0a1a2e] backdrop-blur-md',
      text: 'text-[#c0c9d3]',
      inputBg: 'bg-[#1e2d47]',
      inputBorder: 'border-[#3c4a64]',
      inputFocus: 'focus:ring-[#4e5c7a] focus:border-[#5a6a8a]',
      placeholder: 'placeholder-[#586a80]',
      tabActive: 'bg-[#1d2d47] text-white',
      tabHover: 'hover:bg-[#2a3b55]',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-[#1e2d47] hover:bg-[#2a3b55] text-white',
      buttonText: '#fafafa',
      borderColor: 'border-[#3c4a64]',
      buttonHover: 'hover:bg-[#2a3b55]',
      softShadow: 'shadow-md',
      iconColor: 'text-[#9da6b2]', // Icon color based on dark blue theme
    },
    teal: {
      primary: 'bg-teal-500',
      hover: 'hover:bg-teal-600',
      ring: 'focus:ring-teal-400',
      bg: 'bg-teal-800 backdrop-blur-md',
      text: 'text-teal-200',
      inputBg: 'bg-teal-900',
      inputBorder: 'border-teal-700',
      inputFocus: 'focus:ring-teal-400 focus:border-teal-500',
      placeholder: 'placeholder-teal-300',
      tabActive: 'bg-teal-700 text-white',
      tabHover: 'hover:bg-teal-800',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-teal-600 hover:bg-teal-700 text-white',
      buttonText: '#fafafa',
      borderColor: 'border-teal-600',
      buttonHover: 'hover:bg-teal-700',
      softShadow: 'shadow-md',
      iconColor: 'text-teal-400', // Icon color based on teal theme
    },
    indigo: {
      primary: 'bg-indigo-500',
      hover: 'hover:bg-indigo-600',
      ring: 'focus:ring-indigo-400',
      bg: 'bg-indigo-800 backdrop-blur-md',
      text: 'text-indigo-200',
      inputBg: 'bg-indigo-900',
      inputBorder: 'border-indigo-700',
      inputFocus: 'focus:ring-indigo-400 focus:border-indigo-500',
      placeholder: 'placeholder-indigo-300',
      tabActive: 'bg-indigo-700 text-white',
      tabHover: 'hover:bg-indigo-800',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-indigo-600 hover:bg-indigo-700 text-white',
      buttonText: '#fafafa',
      borderColor: 'border-indigo-600',
      buttonHover: 'hover:bg-indigo-700',
      softShadow: 'shadow-md',
      iconColor: 'text-indigo-400', // Icon color based on indigo theme
    },
    light: {
      primary: 'bg-zinc-200',
      hover: 'hover:bg-zinc-300',
      ring: 'focus:ring-zinc-500',
      bg: 'bg-zinc-100 backdrop-blur-md',
      text: 'text-zinc-800',
      inputBg: 'bg-zinc-200',
      inputBorder: 'border-zinc-300',
      inputFocus: 'focus:ring-zinc-400 focus:border-zinc-500',
      placeholder: 'placeholder-zinc-500',
      tabActive: 'bg-zinc-300 text-zinc-800',
      tabHover: 'hover:bg-zinc-400',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-[#18181b] hover:bg-[#18181b] text-[#fafafa]',
      buttonText: '#fafafa',
      borderColor: 'border-zinc-400',
      buttonHover: 'hover:bg-[#18181b]',
      softShadow: 'shadow-md',
      iconColor: 'text-zinc-600', // Icon color based on light theme
    },
    glass: {
      primary: 'bg-gray-900/20',
      hover: 'hover:bg-gray-900/30',
      ring: 'focus:ring-gray-300/70',
      bg: 'bg-gray-900/30 backdrop-blur-lg border border-gray-600/50',
      text: 'text-gray-200',
      inputBg: 'bg-gray-900/70',
      inputBorder: 'border-gray-600/60',
      inputFocus: 'focus:ring-gray-400/80 focus:border-gray-500/70',
      placeholder: 'placeholder-gray-400/80',
      tabActive: 'bg-gray-700 text-white',
      tabHover: 'hover:bg-gray-900/20',
      closeButton: 'bg-red-500 hover:bg-red-600',
      button: 'bg-gray-800/70 hover:bg-gray-800/80 text-white',
      buttonText: '#fafafa',
      borderColor: 'border-gray-600/60',
      buttonHover: 'hover:bg-gray-800/80',
      softShadow: 'shadow-lg',
      iconColor: 'text-gray-400', // Icon color based on glass theme
    },
  };
  
  export default colorPalettes;
  